### ISSUE TITLE
@openshift/dynamic-plugin-sdk or @openshift-console/dynamic-plugin-sdk

### ISSUE THREAD

**Issue by RyanMillerC** [openshift/dynamic-plugin-sdk#210]
Which is correct to use, [@openshift/dynamic-plugin-sdk](https://www.npmjs.com/package/@openshift/dynamic-plugin-sdk) or [@openshift-console/dynamic-plugin-sdk](https://www.npmjs.com/package/@openshift-console/dynamic-plugin-sdk)?

The OpenShift 4.12 docs [here](https://docs.openshift.com/container-platform/4.12/web_console/dynamic-plug-in/dynamic-plug-in-example.html) point to the [openshift/console-plugin-template](https://github.com/openshift/console-plugin-template) repo. That repo is using @openshift-console/dynamic-plugin-sdk.

I noticed that @openshift-console/dynamic-plugin-sdk is missing implementations of [documented](https://docs.openshift.com/container-platform/4.12/web_console/dynamic-plug-in/dynamic-plug-ins-reference.html#dynamic-plug-in-api_dynamic-plug-ins-reference) functions like k8sListResource, k8sCreateResource, etc. The types are there but the implementation isn't. Those functions are implemented [in this repo](https://github.com/openshift/dynamic-plugin-sdk/blob/main/packages/lib-utils/src/k8s/k8s-resource.ts) though.

**Comment by vojtechszocs** [comment]
Hello @RyanMillerC 

> Which is correct to use, [@openshift/dynamic-plugin-sdk](https://www.npmjs.com/package/@openshift/dynamic-plugin-sdk) or [@openshift-console/dynamic-plugin-sdk](https://www.npmjs.com/package/@openshift-console/dynamic-plugin-sdk)?

OpenShift Console 4.12 uses its own plugin SDK implementation via `@openshift-console/dynamic-plugin-sdk` and `@openshift-console/dynamic-plugin-sdk-webpack` packages. When writing a plugin for OpenShift Console 4.12 or earlier, you should use these packages.

See "OpenShift Console Versions vs SDK Versions" section in [Console plugins README](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/README.md) which maps Console release versions to plugin SDK package versions.

> I noticed that @openshift-console/dynamic-plugin-sdk is missing implementations of [documented](https://docs.openshift.com/container-platform/4.12/web_console/dynamic-plug-in/dynamic-plug-ins-reference.html#dynamic-plug-in-api_dynamic-plug-ins-reference) functions like k8sListResource, k8sCreateResource, etc. The types are there but the implementation isn't.

Console K8s utility functions like `k8sListResource` are declared [here](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts) - these are typically wrapped via `adapterFunc` for backwards API compatibility.

These utilities should be available through `@openshift-console/dynamic-plugin-sdk` package in terms of both code and typings :thinking: when you clone Console repo and run `yarn install` it will automatically rebuild all Console plugin SDK dist packages at `frontend/packages/console-dynamic-plugin-sdk/dist`.

The `core` subdirectory is for `@openshift-console/dynamic-plugin-sdk` package published to npmjs. Console `k8sListResource` and other K8s utilities are in `lib/utils/k8s/k8s-resource.js` under this subdirectory.

I think the issue may be with export name - the function is exported under name `k8sList` and not `k8sListResource`.
```ts
export {
  k8sGetResource as k8sGet,
  k8sCreateResource as k8sCreate,
  k8sUpdateResource as k8sUpdate,
  k8sPatchResource as k8sPatch,
  k8sDeleteResource as k8sDelete,
  k8sListResource as k8sList,
  k8sListResourceItems as k8sListItems,
} from '../utils/k8s';
```

> Those functions are implemented [in this repo](https://github.com/openshift/dynamic-plugin-sdk/blob/main/packages/lib-utils/src/k8s/k8s-resource.ts) though.

Right, we copied Console K8s utility functions into this repo and tweaked them a bit. But we export them as e.g. `k8sListResource` instead of `k8sList` which is likely the source of confusion :smiley:

**Comment by vojtechszocs** [comment]
cc @spadgett

**Comment by RyanMillerC** [comment]
Thanks for the response @vojtechszocs.

To be 100% clear, I'm developing a plugin that will be bundled into a community operator. Based on your reply I will use (**@openshift-console**/dynamic-console-plugin and related) that [github.com/openshift/console](https://github.com/openshift/console/tree/master/frontend/packages/console-dynamic-plugin-sdk) provides since I'm targeting OpenShift 4.12 and below.

Are the packages (**@openshift**/dynamic-console-plugin and related) that this repo provides for future versions of OpenShift (4.13 and on)?

---

What threw me off on `k8sListResource` vs `k8sList` is [this comment](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts#L104) that says to use `k8sCreateResource` instead of `k8sCreate`:

```
@deprecated Use {@link k8sCreateResource} instead.
...
export const k8sCreate = <R extends K8sResourceCommon>(
...
```

The other get, create, list *k8sActionResource* functions have a similar deprecated message.
